### ISSUE TITLE
Result video shortage

### ISSUE THREAD

**Issue by Vadim2S** [sstzal/DFRF#10]
I am try few experiments with cnn.mp4 video from you examples. Original has 33 second and produce 840 frames for torso and head.
I am run rendering.sh script with different models and get output videos with 421 frames and 16 second only.

What is it?

**Comment by s1752729916** [comment]
hi, i have the same problem and how you solved it?

**Comment by flyingshan** [comment]
I have the same problem, and I used **ffmpeg** to slow down the result video 2x, and it looked correct, but I dont know why...

**Comment by Teoge** [comment]
I think the video is split into training and validation sets in half. And `rendering.sh` only renders the validation set.

**Comment by AIMads** [comment]
@Teoge  I think so too, I have no clue how it mixes it with the audio.

**Comment by hylq66** [comment]
> @Teoge I think so too, I have no clue how it mixes it with the audio.

Do you know where the audio for the resulting video is stored, the second half of the original audio?

**Comment by hylq66** [comment]
> I think the video is split into training and validation sets in half. And `rendering.sh` only renders the validation set.

Do you know where the audio for the resulting video is stored, the second half of the original audio?

**Comment by cucdengjunli** [comment]
same question

**Comment by sstzal** [comment]
> I think the video is split into training and validation sets in half. And `rendering.sh` only renders the validation set.

It is right.

**Comment by sstzal** [comment]
> > I think the video is split into training and validation sets in half. And `rendering.sh` only renders the validation set.
> 
> Do you know where the audio for the resulting video is stored, the second half of the original audio?

Yes. You just need to combine the generated video with the driven audio you used.
