### ISSUE TITLE
Very slow rendering?

### ISSUE THREAD

**Issue by dourcer** [sstzal/DFRF#13]
run sh rendering.sh
![image](https://user-images.githubusercontent.com/35617526/196579322-9a569fc1-d35f-4bf7-ae4c-57e29ac91a4a.png)
Whether the speed is normal?

**Comment by wytcsuch** [comment]
![image](https://user-images.githubusercontent.com/40099267/207847085-99c34a0e-a2b2-4592-be45-fd4358cf9c38.png)
My pograme runs slower than yours

**Comment by wytcsuch** [comment]
Is this a normal speed ？

**Comment by xiao-lin-hub** [comment]
Hello, have you solved this problem, or is it really so slow

**Comment by exceedzhang** [comment]
> run sh rendering.sh
> ![image](https://user-images.githubusercontent.com/35617526/196579322-9a569fc1-d35f-4bf7-ae4c-57e29ac91a4a.png)
> Whether the speed is normal?

正常速度

**Comment by cucdengjunli** [comment]
same speed

**Comment by kjhgfdsaas** [comment]
same /cry

**Comment by sstzal** [comment]
You can reduce the number of sample nodes in each ray, and reduce the number of rays, and reduce the number of the reference images to acceleration inference, which will not lead to significant performance degradation. Moreover, each frame is independent when inference, so you can use more GPUS for parallel rendering.

**Comment by piwawa** [comment]
![image](https://github.com/sstzal/DFRF/assets/46926496/e49eb720-84ca-4dbd-8156-3442d2ba9af5)

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GRID A100D-3-40C    On   | 00000000:06:00.0 Off |                  N/A |
| N/A   N/A    P0    N/A /  N/A |   5764MiB / 40960MiB |     N/A      Default |
|                               |                      |              Enabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| MIG devices:                                                                |
+------------------+----------------------+-----------+-----------------------+
| GPU  GI  CI  MIG |         Memory-Usage |        Vol|         Shared        |
|      ID  ID  Dev |           BAR1-Usage | SM     Unc| CE  ENC  DEC  OFA  JPG|
|                  |                      |        ECC|                       |
|==================+======================+===========+=======================|
|  0    0   0   0  |   5764MiB / 37611MiB | 42    N/A |  3   0    2    0    0 |
|                  |      2MiB /  4096MiB |           |                       |
+------------------+----------------------+-----------+-----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0    0    0      20004      C   python                           5762MiB |
+-----------------------------------------------------------------------------+
```
Even if on an A100, it's still slow like a snail on a leisurely stroll through peanut butter. This model moves at the pace of a glacier—during an ice age. It's like watching paint dry, if the paint was made of molasses and the wall was in a time warp. If it were any slower, we'd have to measure its speed with a calendar. I mean, I asked it to process some data, and by the time it was done, I had aged enough to consider retirement. It's the digital equivalent of a sloth, on sedatives, stuck in quicksand. If you're in a hurry, better grab a sundial and a comfy chair—it's going to be a while.
