### ISSUE TITLE
deepspeech使用的权重文件

### ISSUE THREAD

**Issue by NingNanXin** [sstzal/DFRF#14]
请问一下你们提取特征用的权重文件是哪个呢？
1. 并没有在deepspeech找到0-1-0的版本，看到在你们的代码中注释了一行0.9.2的 
<img width="609" alt="image" src="https://user-images.githubusercontent.com/56398622/196638010-56424c2f-e210-466b-ac97-13caa10e571e.png">
请问一下用的具体哪个版本呢？

2. 提取中英文特征都是使用英文预训练的模型吗？还是中文采用中文的预训练模型，英文采用英文的预训练模型

**Comment by exceedzhang** [comment]
中文和英文模型是相同的
