### ISSUE TITLE
关于pretrain base model 的一些细节疑问

### ISSUE THREAD

**Issue by YifengMa9** [sstzal/DFRF#15]
您好, 首先感谢您优秀的工作.

关于base model pretraining, 您论文中提及使用3个视频, pretrain 300k step, coarse-to-fine(先不加offset regressor). 对此中细节我有一些疑问.

1. 具体是如何利用3个视频的, 是3个视频依序各训练100k step吗?
2. 300k step 是怎么分配的?  比如: 从多少个step 开始加入offset regressor? 3个视频按照何次序各训练多少step?
3. 您的代码offset regressor和其他部分紧密耦合, 所以pretrain阶段您是用另外的代码训练的吗?

再次感谢您的研究对talking head 领域带来的启发. 期待您的回信!

**Comment by kangzhao2** [comment]
+1

**Comment by cucdengjunli** [comment]
+1

**Comment by sstzal** [comment]
1. 视频都切成帧，训练时完全混和随机采样
2. 先训300k,再加上offset regressor再训100k.3个视频时完全混和的，没有顺序
3. 并不是完全耦合，但是我确实没有在github上放不加offset regressor的代码。你可以直接使用加了offset regressor的代码训练400k得到 base model,这个影响不大。
