### ISSUE TITLE
how to make a output video with the rendered images and input audio ?

### ISSUE THREAD

**Issue by kyuhyoung** [sstzal/DFRF#19]
Thank you for this amzaing code share.

As I understand so far, the result of 'redering.sh' is a sequence of images files.  To check the quality of the result, we have to watch the synthesized video (with the input audio).  I do not see the script for making the synthesized video.  Can somebody tell me where is the script?

**Comment by cucdengjunli** [comment]
same question

**Comment by sstzal** [comment]
> Thank you for this amzaing code share.
> 
> As I understand so far, the result of 'redering.sh' is a sequence of images files. To check the quality of the result, we have to watch the synthesized video (with the input audio). I do not see the script for making the synthesized video. Can somebody tell me where is the script?

Combining imgs into video is simple work. Such script can be easily searched on the network.
