### ISSUE TITLE
More details of training base model

### ISSUE THREAD

**Issue by Songlin-Yang** [sstzal/DFRF#2]
Hi! Shuai~
Thank you for your great and inspiring work first !
I want to change your network for my application, and the detials of training base model are important to me.
Can you provide the instructions of training the base model, or how many data do you use for training it ?

**Comment by Songlin-Yang** [comment]
Do you use only the 12 public videos to train your base model?

**Comment by sstzal** [comment]
No. We use three videos to train the base model, which is mentioned in 4.1. And there is no overlap between these three ids and the generated results shown in the demo.

**Comment by JunjieLl** [comment]
> No. We use three videos to train the base model, which is mentioned in 4.1.

You mean I need execute the script `run.sh` step by step like `run.sh 0 && run.sh 1 && run.sh 2`?

Could you give me more guidance about the description: 
>We select three videos from different races and languages (English and Chinese), and combine them into a three-minute video to train the base model.

what is the meaning of combine ?
