### ISSUE TITLE
Clarification on how to use this?

### ISSUE THREAD

**Issue by AIMads** [sstzal/DFRF#22]
Great work with alot of potential, but we need clarification on how to use it. 

1. After you have trained a model, how do you then change the audio so you can do a new rendering on that audio instead of the one used for training?

2. How do you create this as an output video with the rendered images and the audio?

I have trained a model on my own video clip now, but don't now what to do with it.

**Comment by CODER4715** [comment]
+1

**Comment by CODER4715** [comment]
I appreciate your work，and i want to know how to make a new video with a new audio and trained model

**Comment by exceedzhang** [comment]
me too

**Comment by wzx7084** [comment]
+1

**Comment by dafang** [comment]
+1 @sstzal

**Comment by sstzal** [comment]
Refer to https://github.com/sstzal/DFRF/issues/10
