### ISSUE TITLE
Multy-GPU training?

### ISSUE THREAD

**Issue by Vadim2S** [sstzal/DFRF#4]
I am have PC with two old GPU. I am set CUDA_VISIBLE_DEVICES=0,1 and launch "run.sh". Unfortunate only first GPU in usage with terrifing ~300 hours for training. 

Is here GPU limitation somewhere in code?

**Comment by sstzal** [comment]
We did not implement multi-GPU training. If it is needed, you can realize it yourself by referring to some existing repos which have deployed the NeRF on multiple GPUs.

**Comment by cucdengjunli** [comment]
same question
