### ISSUE TITLE
process_data looking for track_params.pt

### ISSUE THREAD

**Issue by skunkwerk** [sstzal/DFRF#8]
thank you for this code repository.

I was able to follow the instructions and tried to run 
!sh process_data.sh cnn2_25fps

but I run into this error:
Traceback (most recent call last):
  File "data_util/process_data.py", line 295, in <module>
    params_dict = torch.load(os.path.join(id_dir, 'track_params.pt'))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/cnn2_25fps/0/track_params.pt'

where would I find this model?

this is what the folder currently contains:
![Screen Shot 2022-08-30 at 11 59 44 PM](https://user-images.githubusercontent.com/64326/187596173-9bc30328-c42e-4282-acf5-12fc60449eb2.png)

**Comment by YifengMa9** [comment]
`track_params.pt` is the result of preprocessing step 6. I guess you did not run step 6 successfully, which runs a face tracker.

**Comment by sstzal** [comment]
> `track_params.pt` is the result of preprocessing step 6. I guess you did not run step 6 successfully, which runs a face tracker.

Right.
